Feature/login
teamcodingmobile/discourse-ios pull request #13
Opened 2020-11-03 18:50 UTC by aarcala10

Add GetLogin

2020-11-03 19:56 UTC, gricob commented on discourse/Data/Models/UserLogin.swift
> +struct UserLogin: Codable{
En Data/Models solo deberían estar modelos del dominio de aplicación, es decir, que no tengan que ver con la API. UserLogin forma parte de la repuesta, por lo que debería estar junto a GetLoginResponse

2020-11-03 19:56 UTC, gricob commented on discourse/ViewController.swift
> +    var client: HttpClient?
En el Controllers/ViewModels se debe de usar DataClient con un @Inject

2020-11-03 19:56 UTC, gricob commented on discourse/Data/Client/DataClient.swift
> +    func getLogin(atUser username: String, onSuccess success: @escaping(UserLogin) -> (), onError error: ((Error?)-> ())?) -> Void
Realmente login en sí ya es la acción. Igual la función debería llamarse simplemente login.
Por otro lado, en lugar de _atUser_ creo que encaja más _withUser_ o _usingUser_

2020-11-03 19:56 UTC, gricob commented on discourse/Data/Client/Http/HttpClient.swift
> +            if self != nil {
Hay que tener en cuenta que cuando la llamada de login es satisfactoria, debe de algún modo almacenarse el usuario que ha iniciado sesión para poder añadirlo en cada llamada. 
La opción rápida que se me ocurre es que en el propio HttpClient se almacene el valor en una propiedad authenticatedUser. Que por defecto tenga el valor _system_ y que cuando se produzca un login satisfactorio cambie al username del usuario que ha iniciado sesión. 
Esto implicaría cambiar el HttpRequest para que no incluya header Api-Username y sea HttpClient quien se encargue de hacerlo.

2020-11-03 19:56 UTC, gricob commented on discourse/Data/Factory/LoginFactory.swift
> +    func create(from response: GetLoginResponse) -> UserLogin {
La factory cobra sentido para cambiar de un modelo de respuesta a uno del dominio de aplicación. En este caso, los dos que estás usando son de respuesta, por lo que sería lo mismo que no usar la factory y en el success directamente pasarle response.user

2020-11-03 21:54 UTC, aarcala10 commented on discourse/ViewController.swift
> +    var client: HttpClient?
Si esto lo había puesto por probar a ver q fallaba... se me ha olvidado borrarlo

2020-11-03 21:56 UTC, aarcala10 commented on discourse/Data/Client/Http/HttpClient.swift
> +            if self != nil {
Lo malo de hacerlo así que cada vez que cierres la app tienes que loguearte, lo bueno seria en guardarlo en coreData o simplemente en userPreferences...

2020-11-03 21:57 UTC, aarcala10 commented on discourse/Data/Factory/LoginFactory.swift
> +    func create(from response: GetLoginResponse) -> UserLogin {
Tienes toda la razón..

2020-11-03 21:57 UTC, aarcala10 commented on discourse/Data/Models/UserLogin.swift
> +struct UserLogin: Codable{
Tienes razón...

2020-11-04 07:12 UTC, gricob commented on discourse/Data/Client/Http/HttpClient.swift
> +            if self != nil {
Igual podemos crear un protocol Authentication que tenga un método authenticate que guarde el usuario en userPreferences y otro getUsername que te devuelva el username del usuario e inyectarselo al httpClient

2020-11-07 08:53 UTC, gricob requested changes
Hay que añadir el AuthService para gestionar cuando el usuario tiene la sesión iniciada y cuando no. Este servicio se encargará de almacenar el username del usuario en UserPreferences para no tener que iniciar sesión cada vez que se abra la app

2020-11-07 11:27 UTC, ssieiro commented on discourse/Data/Client/DataClient.swift
> +    func getLogin(atUser username: String, onSuccess success: @escaping(UserLogin) -> (), onError error: ((Error?)-> ())?) -> Void
Aquí finalmente se va a poner "login" a la función en lugar de getLogin?

2020-11-09 17:22 UTC, gricob requested changes

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/DataClient.swift
> +    func getLogin(withUser username: String, onSuccess success: @escaping(UserLogin) -> (), onError error: ((Error?)-> ())?) -> Void
La acción es login, no getLogin. Por otro lado, no es necesario que devuelva nada, por lo que el closure success no requiere argumentos

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/Http/HttpClient.swift
> +    let authService = AuthService()
AuthService debería ser un servicio inyectado para seguir con la inyección de dependencias. Si no te aclaras con el resolve si quieres déjalo así y ya lo cambiaremos

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/Http/HttpClient.swift
> +                success(response!.user)
Success debería de ir después de notificar al authService de que se ha iniciado sesión. Si lo dejas en este orden, estás acabando el proceso antes de finalizarlo del todo

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/Http/Request/GetLoginRequest.swift
> +struct GetLoginRequest: HttpRequest {
Login es la acción, por lo que el request debería de llamarse LoginRequest

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/Http/Response/GetLoginResponse.swift
> +struct GetLoginResponse: Codable{
Lo dicho en la request. El nombre debería ser LoginResponse

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Models/AuthService.swift
> +struct AuthService {
Más que un struct creo que encajaría más un protocol que defina los métodos y una extensión que implemente los métodos usando UserDefaults.
Por otro lado, echo en falta un método _isLogged_ que devuelva true o false en función de si el usuario está loggeado o no. 
Y otro _loggedUser_ que devuelva el usuario que tiene la sesión iniciada si es que hay alguno.

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/Http/Request/HttpRequest.swift
> +        let userLoged = authService.log.value(forKey: "user") as? String ?? "system"
Si lo haces así, no podrías reemplazar la forma en la que se obtiene el usuario loggeado sin afectar a esta parte del código. HttpRequest solo debería conocer los métodos que ofrece AuthService y no debería hacer uso de UserDefaults. Esto es así para evitar que, si por ejemplo cambias la forma en la que se almacena el usuario loggeado, no tengas que modificar esta clase sino que solo tengas que modificar AuthService

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/Http/Request/HttpRequest.swift
> +        let authService = AuthService()
Este tipo de servicios es mejor inyectarlos para que si en algún momento cambias el modo en que inicias sesión no tengas que cambiar esta clase

2020-11-09 17:22 UTC, gricob commented on discourse/Data/Client/Http/Request/HttpRequest.swift
> +        urlRequest.addValue(userLoged, forHTTPHeaderField: "Api-Username")
Igual esto se puede mover a HttpClient y así evitas tener AuthService inyectado en los dos sitios

2020-11-12 18:08 UTC, gricob approved these changes

2020-11-12 18:11 UTC, merged